"""Constants for the PACEEX BMS integration."""

DOMAIN = "paceex_bms"
CONF_PORT = "port"
CONF_SCAN_INTERVAL = "scan_interval"

DEFAULT_PORT = 8888
DEFAULT_SCAN_INTERVAL = 30
MIN_SCAN_INTERVAL = 5
UNAVAILABLE_AFTER_FAILURES = 3

MANUFACTURER = "PeiCheng Technology"
MODEL = "PACEEX Smart BMS"
